apiVersion: apps/v1
kind: Deployment
metadata:
  # tên của deployment
  name: checkinpro-api
spec:
  # số POD tạo ra
  replicas: 1

  # thiết lập các POD do deploy quản lý, là POD có nhãn  "app=deployapp"
  selector:
    matchLabels:
      app: checkinpro-api

  # Định nghĩa mẫu POD, khi cần Deploy sử dụng mẫu này để tạo Pod
  template:
    metadata:
      name: podapp
      labels:
        app: checkinpro-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: node
          image: registry.unit.vn/checkinpro-api:1.19
          imagePullPolicy: "Always"
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 5200
      imagePullSecrets:
        - name: registry-gitlab
# kubectl set image deployment/checkinpro-api node=registry.unit.vn/checkinpro-api:1.16 --record
# kubectl set image deployment/nginx-deployment nginx=nginx:1.16.1 --record

